title: Anusree Mondal Rakhi
logo: /Images/headshot_circle.png
description: |
  ML | LLMs | RAG | AI Agents | CV<br>
  Data Scientist<br>
  New York, NY<br>
  Email: <a href="mailto:ar4636@columbia.edu">ar4636@columbia.edu</a><br>
  Phone: <a href="tel:+16317208838">+1 (631) 720-8838</a><br>
  LinkedIn: <a href="https://www.linkedin.com/in/anusreemondalrakhi/">anusreemondalrakhi</a><br>
  Work Authorization: Legal Permanent Resident
theme: jekyll-theme-minimal
show_downloads: false
